#custom_categories:
#  - name: Getting Started 
#    children:
#    - Examples
# source_directory: Delay/
output: ../docs
readme: ../README.md
documentation: ../Documentation/*.md
theme: apple
skip_undocumented: true
hide_documentation_coverage: true
#xcodebuild_arguments:
#  - -workspace
#  - Delay.xcworkspace
#  - -scheme
#  - Delay
author: Eonflux - Hassan Uriostegui
author_url: https://eonflux.io/
github_url: https://github.com/eonfluxor/kron/
